### ISSUE TITLE
Немножко опечаток

### ISSUE THREAD

**Issue by YevgeniyMovsesov** [Infl1ght/skunk_works#4]
с с запада - с запада
Я, как и многие, с работал - Я, как и многие, работал
червёртому - четвёртому
В какой-то эта строительная - В какой-то момент эта строительная
выступая как цирковой прожектор на вражеских радаров.
выступая как цирковой прожектор на вражеских радарах.
чтобы не он не бликовал - чтобы он не бликовал
На самом дела - На самом деле
Возможно, ты прав - Возможно ты прав
Логистика оперции - Логистика операции
поспросили - попросили
ни моей жизни - ни при моей жизни
бомбарщировщика - бомбардировщика
улучшаться в два раза - улучшатся в два раза

**Comment by Infl1ght** [comment]
Спасибо, поправил!
